### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by ronakvbhatt07** [ng2-ui/ng2-map#46]
When I am trying to run using `npm start` in win10 it gives me this 

    \ng2-map\node_modules\.bin\webpack-dashboard:2 
     basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
    SyntaxError: missing ) after argument list
        at Object.exports.runInThisContext (vm.js:76:16)
        at Module._compile (module.js:528:28)
        at Object.Module._extensions..js (module.js:565:10)
        at Module.load (module.js:473:32)
        at tryModuleLoad (module.js:432:12)
        at Function.Module._load (module.js:424:3)
        at Module.runMain (module.js:590:10)
        at run (bootstrap_node.js:394:7)
        at startup (bootstrap_node.js:149:9)
        at bootstrap_node.js:509:3

Is there anything that i am missing?

**Comment by allenhwkim** [comment]
I think it's a matter of webpack-dashboard. There must be a bug for it.

    "start": "NODE_ENV=dev node node_modules/.bin/webpack-dashboard --title ng2-map -- node_modules/.bin/webpack-dev-server --quiet --port 9001 --content-base app --config app/webpack.config --open"

Can you start webpack-dashboard manually?

**Comment by allenhwkim** [comment]
I don't think webpack-dashboard is ready for Windows.
Please use the following command manually for windows

 `node_modules/.bin/webpack-dev-server --quiet --port 9001 --content-base app --config app/webpack.config --open`
