### ISSUE TITLE
cannot npm install under windows 7

### ISSUE THREAD

**Issue by phil123456** [ng2-ui/ng2-map#50]
Hi,

first I had to install 'win-node-env' cos NODE_ENV was not recognized as a standard command
but yet I get this error doing 'npm start'
```

D:\WORK\ANGULAR\ng2-map-master>npm start

> ng2-map@0.9.2 start D:\WORK\ANGULAR\ng2-map-master
> NODE_ENV=dev node node_modules/.bin/webpack-dashboard --title ng2-map -- node_modules/.bin/webpack-dev-server --quiet --port 9001 --content-base app --config app/webpack.config --open

D:\WORK\ANGULAR\ng2-map-master\node_modules\.bin\webpack-dashboard:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

also sed is a linux command so I guess your project cannot be started under windows

**Comment by allenhwkim** [comment]
We need to re-think using webpack-dashboard because it seems not ready for Windows.

**Comment by phil123456** [comment]
Ok so I am screwed

I don’t understand the point of using nodejs if projects are strongly linked to their native environement

**Comment by allenhwkim** [comment]
That does not mean end of the world :)

Try this way also

```
node_modules/.bin/webpack-dev-server --config app/webpack.config.js --content-base app --open 
```

**Comment by aitboudad** [comment]
see https://github.com/formly-js/ng2-formly/pull/295/files for changes needed to make it work on windows 
I would help but I don't have much time these days :)

**Comment by phil123456** [comment]
Got no .bin in node_modules directory :-(

**Comment by allenhwkim** [comment]
@phil123456 thanks for letting me know that it's not convenient on Windows 7. If you have any better solution, please let us know.

**Comment by phil123456** [comment]
actually the slash need to be backslah...usual windows bs

```
D:\WORK\ANGULAR\ng2-map-master>node_modules\.bin\webpack-dev-server --config app/webpack.config.js --content-base app --open
 http://localhost:8080/webpack-dev-server/
webpack result is served from /build/
content is served from D:\WORK\ANGULAR\ng2-map-master\app
ts-loader: Using typescript@2.0.10 and D:\WORK\ANGULAR\ng2-map-master\tsconfig.json

```
