### ISSUE TITLE
How to include this module into Webpack

### ISSUE THREAD

**Issue by Dralac** [ng2-ui/ng2-map#7]
More question than the issue, but I'd appreciate if you an post some code how to make this work with webpack when you grab a second.
I'm trying to make it work with universal-starter here: https://github.com/angular/universal-starter/blob/master/webpack.config.js

My Component: 
```javascript
import { Component, OnInit } from '@angular/core';
import { NG2_MAP_DIRECTIVES, Ng2MapComponent } from "ng2-map";  // <--- this

@Component({
  selector: 'map',
  templateUrl: 'map.template.html',
  directives: [ NG2_MAP_DIRECTIVES ]
})
export class Map {
  constructor(){
    Ng2MapComponent.apiUrl = "https://maps.google.com/maps/api/js?key=YOUR_KEY";
  }
}
```
Console output:
```javascript
ERROR in ./~/ng2-map/dist/components/ng2-map.component.ts
(157,31): error TS2304: Cannot find name 'google'.
ERROR in ./src/app/partials/map/map.component.ts
(21,21): error TS2339: Property 'apiUrl' does not exist on type 'typeof Ng2MapComponent'.
```

Thanks

**Comment by allenhwkim** [comment]
```
ERROR in ./~/ng2-map/dist/components/ng2-map.component.ts
(157,31): error TS2304: Cannot find name 'google'.

```
This happens because there is no type 'google' defined. You can install 'google.maps' as a typings. This is my typings.json

```
{
  "globalDependencies": {
    "core-js": "registry:dt/core-js#0.0.0+20160602141332",
    "jasmine": "registry:dt/jasmine#2.2.0+20160621224255",
    "google.maps": "registry:dt/google.maps#3.20.0+20160414124451",
    "node": "registry:dt/node#6.0.0+20160602155235"
  }
}

```


```
ERROR in ./src/app/partials/map/map.component.ts
(21,21): error TS2339: Property 'apiUrl' does not exist on type 'typeof Ng2MapComponent'.
```

This happens because there is no variable defined `apiUrl` in Ng2MapComponent.
Personally I don't mind this way, but it complains use `['...']` notation instead

`Ng2MapComponent['apiUrl'] = "https://maps.google.com/maps/api/js?key=YOUR_KEY"; `

**Comment by Dralac** [comment]
Hi @allenhwkim, 

This solution fixed the issues I had before, but I'm afraid I'm getting new error now: 

```javascript
Listening on: http://localhost:3000
EXCEPTION: Error: Uncaught (in promise): No Directive annotation found on Ng2MapComponent
STACKTRACE:
Error: Uncaught (in promise): No Directive annotation found on Ng2MapComponent
    at resolvePromise (c:\server\project\universal-starter\node_modules\angular2-universal\node_modules\angular2-universal-polyfills\node_modules\zone.js\dist\zone-node.js:496:32)
    at c:\server\project\universal-starter\node_modules\angular2-universal\node_modules\angular2-universal-polyfills\node_modules\zone.js\dist\zone-node.js:473:14
    at ZoneDelegate.invoke (c:\server\project\universal-starter\node_modules\angular2-universal\node_modules\angular2-universal-polyfills\node_modules\zone.js\dist\zone-node.js:281:29)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (c:\server\project\universal-starter\node_modules\@angular\core\src\zone\ng_zone_impl.js:53:41)
    at ZoneDelegate.invoke (c:\server\project\universal-starter\node_modules\angular2-universal\node_modules\angular2-universal-polyfills\node_modules\zone.js\dist\zone-node.js:280:35)
    at Zone.run (c:\server\project\universal-starter\node_modules\angular2-universal\node_modules\angular2-universal-polyfills\node_modules\zone.js\dist\zone-node.js:174:44)
    at c:\server\project\universal-starter\node_modules\angular2-universal\node_modules\angular2-universal-polyfills\node_modules\zone.js\dist\zone-node.js:529:58
    at ZoneDelegate.invokeTask (c:\server\project\universal-starter\node_modules\angular2-universal\node_modules\angular2-universal-polyfills\node_modules\zone.js\dist\zone-node.js:314:38)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (c:\server\project\universal-starter\node_modules\@angular\core\src\zone\ng_zone_impl.js:44:41)
    at ZoneDelegate.invokeTask (c:\server\project\universal-starter\node_modules\angular2-universal\node_modules\angular2-universal-polyfills\node_modules\zone.js\dist\zone-node.js:313:43)
```

Code is the same like above with few adjustments as you proposed: 

```javascript
import { Component, OnInit } from '@angular/core';
import { NG2_MAP_DIRECTIVES, Ng2MapComponent } from "ng2-map";

@Component({
  selector: 'map',
  templateUrl: 'map.template.html',
  directives: [ NG2_MAP_DIRECTIVES ]
})

export class Map {

  constructor(){
    Ng2MapComponent['apiUrl'] = "https://maps.google.com/maps/api/js?key=MY_API_KEY";
  }

  ngOnInit(){
    this.apiService.onDataSourceChange.subscribe(
    // do stuff
    );
  }
}
```

And my map.template.html is exactly the same like in your demo:
```html
<ng2-map center="Brampton, Canada">
    <marker position="Brampton, Canada" draggable="true"></marker>
</ng2-map>
```

Please let me know if you have any idea what could be wrong.
